spring:
  main:
    banner-mode: console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/KeyGenerator
    url: jdbc:mysql://212.24.97.38:3306/key_generator_db
    #    username: KeyGenAdmin
    username: AndriusDau
    #    password: password
    password: AND2024*006msqL
    hikari:
      maximum-pool-size: 100


  jpa:
    # defer-datasource-initialization = reiklainga kad pirma idiegtu lenteles o poto jas uzpildytu
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    #      dml-auto: always
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/dml-scripts.sql
  #      schema-locations: classpath:db/ddl-scripts.sql
  #  security:
  #
  #    user:
  #      name: admin
  #      password: admin123@#$
  # naudosime security is failo
  data:
    web:
      pageable:
        default-page-size: 50

server:
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    lt:
      daujotas:
        KeyGenerator:
          config: DEBUG
          product: INFO
          filter: TRACE
    org:
      springframework:
        security: DEBUG