spring:
  main:
    banner-mode: console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KeyGenerator
    username: KeyGenAdmin
    password: password

  #  sql:
  #    init:
  #      schema-locations: classpath:db/ddl-scripts.sql
  #      data-locations: classpath:db/dml-scripts.sql
#  security:
#
#    user:
#      name: admin
#      password: admin123@#$
# naudosime security is failo

  jpa:
    hibernate:
      ddl-auto: validate
      dml-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 50

  thymeleaf:
#    prefix: file:src/main/resources/templates/
    cache: false


server:
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    lt:
      daujotas:
        KeyGenerator:
          config: DEBUG
          product: INFO
          filter: TRACE

