spring:
  main:
    banner-mode: console
#cia tuo atveju jei turim H2 DB ir SecurityConfig class
#  h2:
#    console:
#      path: eshop_h2
#      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KeyGenerator
    username: KeyGenAdmin
    password: password

  #  sql:
  #    init:
  #      schema-locations: classpath:db/ddl-scripts.sql
  #      data-locations: classpath:db/dml-scripts.sql
  security:
    user:
      name: admin
      password: admin123@#$

  jpa:
    hibernate:
      ddl-auto: update
      dml-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  data:
    web:
      pageable:
        default-page-size: 50

  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  resources:
    cache-period: 0



